### ISSUE TITLE
[Bug]: Monitor.lua nil value error

### ISSUE THREAD

**Issue by francisalbar** [Caedilla/RSA#12]
### Description

Message: Interface/AddOns/RSA/Tools/Monitor.lua:395: attempt to index local 'currentSpell' (a nil value)

### RSA Version

RSA 5.9.0-alpha

### World of Warcraft Flavor

Dragonflight

### Lua Error

Message: Interface/AddOns/RSA/Tools/Monitor.lua:395: attempt to index local 'currentSpell' (a nil value)
Time: Wed Dec 14 09:30:58 2022
Count: 5
Stack: Interface/AddOns/RSA/Tools/Monitor.lua:395: attempt to index local 'currentSpell' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/RSA/Tools/Monitor.lua"]:395: in function <Interface/AddOns/RSA/Tools/Monitor.lua:363>

Locals: 

### Reproduction Steps

Loading 5.9.0-alpha

**Comment by francisalbar** [comment]
Adding `if currentSpell then` block before Monitor.lua:395 seems to fix

**Comment by Caedilla** [comment]
Fixed in 5.9.1
