### ISSUE TITLE
[Bug]: warlock RSA not working

### ISSUE THREAD

**Issue by Milky063** [Caedilla/RSA#18]
### Description

So RSA isn't working for my alts, it actually works fine for my main (priest) but for my mage and warlock its not working at all. I've deleted it and reinstalled it but still nothing. 

### RSA Version

5.15

### World of Warcraft Flavor

Dragonflight

### Lua Error

none

### Reproduction Steps

reinstalled

**Comment by Milky063** [comment]
So its been 3 weeks and this addon is still isn't working.....anyone?

**Comment by Milky063** [comment]
I also reinstalled about 34 times, i reset the warlock settings about 43 times as well. it calls out healthstones fine but when you try to summon someone it doesn't come up at all with a message.

**Comment by porkchop520** [comment]
Confirmed that this is still an issue. Ritual of Summoning does not announce properly.

**Comment by porkchop520** [comment]
@Caedilla I was able to fix the Ritual of Summoning issue by changing the event its looking for from SPELL_CAST_START to SPELL_CAST_SUCCESS in the Warlock file as seen in the combat log for this particular spell:

11/28 22:32:59.758  SPELL_CAST_SUCCESS,Player-3676-0E36DE73,"Xeoro-Area52",0x10511,0x0,0000000000000000,nil,0x80000000,0x80000000,698,"Ritual of Summoning",0x20,Player-3676-0E36DE73,0000000000000000,655179,655179,1220,12257,5041,98276,0,250000,250000,12500,23.93,-866.14,2112,5.1498,455

**Comment by Milky063** [comment]
yup i gave up on this lol

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
