### ISSUE TITLE
[Enhancement]: Cata - Add Power Word: Barrier to list of spells to make announcements 

### ISSUE THREAD

**Issue by Raina1007** [Caedilla/RSA#22]
**Is your feature request related to a problem? Please describe.**
Missing Discipline Priest Power Word: Barrier from list of spells that can be announced

**Describe the solution you'd like**
Just add it as one of the options

**Additional context**
i have attached two screenshot showing spell id, hopefully this helps

<img width="255" alt="Screenshot 2024-07-03 at 11 36 08 AM" src="https://github.com/Caedilla/RSA/assets/72997449/42b0abfc-4173-4131-a075-4951a113873c">
<img width="165" alt="Screenshot 2024-07-03 at 11 35 47 AM" src="https://github.com/Caedilla/RSA/assets/72997449/b13f3579-24b1-4cd8-bf63-83836058c6ef">

**Comment by Raina1007** [comment]
1st image is when its being used and the buff that people get when inside, 2nd image is the spell on my action bar unused

**Comment by Caedilla** [comment]
Added in 5.4
