### ISSUE TITLE
[Bug]: New update doens't feature whispering properly

### ISSUE THREAD

**Issue by wwbrandon** [Caedilla/RSA#28]
### Description

Tries to whisper the person as if they were on your server. Without the " -server " addition

### RSA Version

new version

### World of Warcraft Flavor

Dragonflight

### Reproduction Steps

whisper anyone through RSA says no player playing

**Comment by BlueNightSky** [comment]
There is no error in the addon itself (v5.3.1), but the Announcement cannot work (Smart Group).

**Comment by Caedilla** [comment]
Fixed in 5.3.1
