### ISSUE TITLE
[Bug]: Portal: Dornogal not detected by addon.

### ISSUE THREAD

**Issue by Poccket** [Caedilla/RSA#29]
### Description

When casting Portal: Dornogal, the addon does not detect it. All other portals are detected.

### RSA Version

RSA 5.3.1

### World of Warcraft Flavor

War Within

### Reproduction Steps

1. Cast Portal: Dornogal
2. No message is printed.

### Screenshots

![image](https://github.com/user-attachments/assets/42bb1a83-4043-461f-b2c1-30e294b9df51)
![image](https://github.com/user-attachments/assets/e802a09e-20af-4908-be3e-42cb5927ac0a)

**Comment by Bugsbolt** [comment]
I'm not the author, but if you go into the retail/interface/addons/RSA/SpellData . Then open the mage.lua (can open it in notepad for this) From here what I did was ctrl+f for an portal that was announcing, I searched for Stormwind for this. Then you can just add this line to the bottom of the list of portals:
				[446534] = true, -- Dornogal
and you go to the next instance of Stormwind you can add this line to the bottom of that list:
				[446540] = true, -- Dornogal
This is the teleport spellID so it'll yell at you if you're teleporting without friends and whatnot. But this worked for me, it's announcing properly now.

**Comment by Caedilla** [comment]
Thanks for doing the legwork for me with the spell IDs. 

It's added in 5.4.
