### ISSUE TITLE
Tossing Error on Retail.

### ISSUE THREAD

**Issue by greenstones** [Caedilla/RSA#5]
1x Interface/AddOns/RSA_Options/Options.lua:2134: attempt to concatenate a nil value
[string "@Interface/AddOns/RSA_Options/Options.lua"]:2134: in function <Interface/AddOns/RSA_Options/Options.lua:1991>
[string "@Interface/AddOns/RSA_Options/Options.lua"]:3226: in function `FixDB'
[string "@Interface/AddOns/RSA_Options/Options.lua"]:3709: in function <Interface/AddOns/RSA_Options/Options.lua:3699>
[string "=[C]"]: ?
[string "@Interface/AddOns/RSA/Core.lua"]:170: in function <Interface/AddOns/RSA/Core.lua:12>
[string "=[C]"]: ?

Version: RSA-r547-Release.zip
(Which is the most current version on curse.  Although it says updated 15 hours ago and the date is November 20, 2021)

Info: Basically it tosses the error on load bugsack/bugrabber shows it is tainting other another addon called CoordsTracking which works fine without RSA loaded.

**Comment by Caedilla** [comment]
That's an outdated release version - there was an update, a new alpha version. Said alpha version is the only version right now that supports Dragonflight. I hope to have a full release out soon.
