### ISSUE TITLE
[Bug]: Consistently getting this error and announcements don't work.

### ISSUE THREAD

**Issue by Bugasum** [Caedilla/RSA#7]
### Description

Just keep getting this error over and over with no announcements working.

1x RSA/Tools/Monitor.lua:160: Usage: UnitGUID("unit")
[string "=[C]"]: in function `UnitGUID'
[string "@RSA/Tools/Monitor.lua"]:160: in function <RSA/Tools/Monitor.lua:145>
[string "@RSA/Tools/Monitor.lua"]:183: in function `ProcessSpell'
[string "@RSA/Tools/Monitor.lua"]:371: in function <RSA/Tools/Monitor.lua:327>

Locals:
(*temporary) = <table> {
 1 = "player"
}

### RSA Version

5.6.2

### World of Warcraft Flavor

Dragonflight

### Lua Error

1x RSA/Tools/Monitor.lua:160: Usage: UnitGUID("unit")
[string "=[C]"]: in function `UnitGUID'
[string "@RSA/Tools/Monitor.lua"]:160: in function <RSA/Tools/Monitor.lua:145>
[string "@RSA/Tools/Monitor.lua"]:183: in function `ProcessSpell'
[string "@RSA/Tools/Monitor.lua"]:371: in function <RSA/Tools/Monitor.lua:327>

Locals:
(*temporary) = <table> {
 1 = "player"
}

### Reproduction Steps

Happens with any group as soon as a spell is used.

**Comment by Caedilla** [comment]
This should be fixed in 5.7.0
